<?php
/**
 * อ่าน data/fwd-pages/*.htm → สร้าง data/plans-detail-imported.json
 * Usage: php scripts/import-fwd-pages-to-details.php
 */
require_once __DIR__ . '/../includes/fwd-parse-htm.php';

$root = dirname(__DIR__);
$catalogList = json_decode(file_get_contents($root . '/data/fwd-urls/all-products.json'), true);
$catalogBySlug = [];
foreach ($catalogList as $row) {
    $catalogBySlug[$row['slug']] = [
        'slug' => $row['slug'],
        'title' => $row['title'],
        'desc' => '',
        'category' => $row['category'],
        'category_label' => $row['category_label'],
    ];
}

$defs = require $root . '/includes/plans-catalog-definitions.php';
foreach ($defs as $catId => $cat) {
    foreach ($cat['products'] as $p) {
        $catalogBySlug[$p['slug']]['desc'] = $p['desc'] ?? '';
        if (!empty($p['discount'])) {
            $catalogBySlug[$p['slug']]['discount'] = $p['discount'];
        }
    }
}

$pagesDir = $root . '/data/fwd-pages';
$imported = [];
$stats = ['full' => 0, 'meta_only' => 0, 'missing_file' => 0];

$pageAliases = [
    'fwd-power-saving' => 'fwd-power-saving-12-6',
];

foreach ($catalogBySlug as $slug => $catalog) {
    $pageSlug = $pageAliases[$slug] ?? $slug;
    $file = $pagesDir . '/' . $pageSlug . '.htm';
    if (!is_readable($file)) {
        $stats['missing_file']++;
        continue;
    }
    $html = file_get_contents($file);
    $detail = fwd_parse_htm_to_plan_detail($html, $catalog);
    if (!empty($detail['coverage_blocks']) || count($detail['faq']) > 2) {
        $stats['full']++;
    } else {
        $stats['meta_only']++;
    }
    if (!empty($catalog['discount'])) {
        $detail['discount'] = $catalog['discount'];
    }
    $imported[$slug] = $detail;
}

$jsonPath = $root . '/data/plans-detail-imported.json';
file_put_contents(
    $jsonPath,
    json_encode($imported, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
);

$phpPath = $root . '/includes/plans-detail-imported.php';
$export = var_export($imported, true);
$php = "<?php\n/** Auto-generated by scripts/import-fwd-pages-to-details.php */\nreturn $export;\n";
file_put_contents($phpPath, $php);

echo "Imported " . count($imported) . " plans\n";
echo "  full content: {$stats['full']}\n";
echo "  meta/basic:   {$stats['meta_only']}\n";
echo "  missing file: {$stats['missing_file']}\n";
echo "JSON: $jsonPath\n";
echo "PHP:  $phpPath\n";
