<?php
/**
 * แคตตาล็อกผลิตภัณฑ์ช่องทางตัวแทน — 37 แผน (ตาม fwd.co.th/th/products/)
 * fwd_url = อ้างอิงเนื้อหา (ไม่แสดงลิงก์ออกใน UI)
 * Auto-generated by scripts/build-agent-catalog.php
 */
return array (
  'health' => 
  array (
    'label' => 'ประกันสุขภาพ',
    'products' => 
    array (
      0 => 
      array (
        'slug' => 'health-family-sharing',
        'title' => 'Health Family Sharing',
        'desc' => 'แชร์วงเงินสุขภาพในครอบครัว',
        'fwd_url' => 'https://www.fwd.co.th/th/health-insurance/health-family-sharing/',
      ),
      1 => 
      array (
        'slug' => 'hospital-benefit',
        'title' => 'Hospital Benefit',
        'desc' => 'เงินชดเชยรายวันเมื่อนอนโรงพยาบาล',
        'fwd_url' => 'https://www.fwd.co.th/th/health-insurance/hospital-benefit/',
      ),
      2 => 
      array (
        'slug' => 'hospital-benefit-plus',
        'title' => 'Hospital Benefit Plus',
        'desc' => 'ผลิตภัณฑ์ เฮชบี พลัส แผนชดเชยรายได้หยุดงานไม่ขาดรายได้ ชดเชยสูงสุด 10,000 บาทต่อวันเมื่อต้องนอนโรงพยาบาล รักษาตัวใน ICU รับเพิ่มเป็น 3 เท่า และรับเงินก้อนกรณ...',
        'fwd_url' => 'https://www.fwd.co.th/th/health-insurance/hospital-benefit-plus/',
      ),
      3 => 
      array (
        'slug' => 'opd-plus',
        'title' => 'OPD Plus',
        'desc' => 'คุ้มครองผู้ป่วยนอกและค่ารักษาเพิ่มเติม',
        'fwd_url' => 'https://www.fwd.co.th/th/health-insurance/opd-plus/',
      ),
      4 => 
      array (
        'slug' => 'precious-care',
        'title' => 'FWD Precious Care',
        'desc' => 'ประกันสุขภาพระดับพรีเมียม วงเงินสูง',
        'fwd_url' => 'https://www.fwd.co.th/th/health-insurance/precious-care/',
      ),
      5 => 
      array (
        'slug' => 'precious-care-for-kids',
        'title' => 'FWD Precious Care for Kids',
        'desc' => 'ประกันสุขภาพสำหรับเด็ก ดูแลตั้งแต่เล็ก',
        'fwd_url' => 'https://www.fwd.co.th/th/health-insurance/precious-care-for-kids/',
      ),
      6 => 
      array (
        'slug' => 'precious-protection',
        'title' => 'FWD Precious Protection',
        'desc' => 'ความคุ้มครองสุขภาพครอบคลุมหลายด้าน',
        'fwd_url' => 'https://www.fwd.co.th/th/health-insurance/precious-protection/',
      ),
      7 => 
      array (
        'slug' => 'prima-care',
        'title' => 'Prima Care',
        'desc' => 'แผนสุขภาพคุ้มค่า เหมาะวัยทำงาน',
        'fwd_url' => 'https://www.fwd.co.th/th/health-insurance/prima-care/',
      ),
    ),
  ),
  'critical' => 
  array (
    'label' => 'ประกันโรคร้ายแรง',
    'products' => 
    array (
      0 => 
      array (
        'slug' => 'cancer-fighter',
        'title' => 'Cancer Fighter',
        'desc' => 'สัญญาเพิ่มเติมประกัน แคนเซอร์ ไฟท์เตอร์ให้คุณพร้อมตั้งรับ กับความคุ้มครองแบบจัดเต็ม เพื่อให้คุณคลายกังวลกับ พร้อมรับมือกับช่วงเวลาท้าทายได้แกร่งกว่าที่คิด',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/cancer-fighter/',
      ),
      1 => 
      array (
        'slug' => 'cancer-knockout',
        'title' => 'Cancer Knockout',
        'desc' => 'ประกันมะเร็ง ต่อสู้โรคร้ายอย่างมั่นใจ',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/cancer-knockout/',
      ),
      2 => 
      array (
        'slug' => 'ci-50',
        'title' => 'CI 50',
        'desc' => 'สัญญาเพิ่มเติมประกันโรคร้าย ซีไอ 50เตรียมพร้อมไว้เสมอ กับแผนประกันที่ออกแบบมาให้คุณพร้อมรับมือกับ 50 โรคร้าย มาเมื่อไหร่ก็รับมือได้ทันที',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/ci-50/',
      ),
      3 => 
      array (
        'slug' => 'ci-all-in-one',
        'title' => 'CI All-in-One',
        'desc' => 'ผลิตภัณฑ์CI ALL-in-Oneแพ็กเกจความคุ้มครองที่ครบในหนึ่งเดียว ตรวจพบ 50 รับเงินก้อน ดูแลต่อเนื่องด้วยแบบเหมาจ่าย และผู้ป่วยใน',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/ci-all-in-one/',
      ),
      4 => 
      array (
        'slug' => 'ci-cash-a-day',
        'title' => 'CI Cash A Day',
        'desc' => 'ผลิตภัณฑ์CI Cash A Dayต่อ เติม เพิ่ม แต่ง เมื่อเข้ารับการรักษาเป็นผู้ป่วยในของรพ. จากการเจ็บป่วยด้วย 50 เพื่อครอบคลุมการดูแลโรคร้าย...',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/ci-cash-a-day/',
      ),
      5 => 
      array (
        'slug' => 'ci-fixed-pay',
        'title' => 'CI Fixed Pay',
        'desc' => 'โรคร้ายแรง จ่ายเงินก้อนตามทุนที่กำหนด',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/ci-fixed-pay/',
      ),
      6 => 
      array (
        'slug' => 'ci-med-all',
        'title' => 'CI Med-ALL',
        'desc' => 'คุ้มครองค่ารักษาและโรคร้ายแรง',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/ci-med-all/',
      ),
      7 => 
      array (
        'slug' => 'ci-reclaim-recare',
        'title' => 'CI Re-Claim Re-Care',
        'desc' => 'ผลิตภัณฑ์CI Re-Claim Re-Careประกันโรคร้าย ดูแลขั้นสุด ครอบคลุมมากถึง 110 โรค เคลมได้สูงสุด 14 ครั้ง ผลประโยชน์รวมสูงสุด 1,100% ของทุนประกันภัย',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/ci-reclaim-recare/',
      ),
      8 => 
      array (
        'slug' => 'ci-reclaim-recare-plus',
        'title' => 'CI Re-Claim Re-Care Plus',
        'desc' => 'ผลิตภัณฑ์CI Re-Claim Re-Care Plusแพ็กเกจความคุ้มครองชีวิตและ เคลมได้สูงสุด 14 ครั้ง และเคลมซ้ำใน 5 ระดับรุนแรงเดิมได้อีกครั้ง ครอบคลุมมากถึง 110 โรคร้...',
        'fwd_url' => 'https://www.fwd.co.th/th/critical-illness-insurance/ci-reclaim-recare-plus/',
      ),
    ),
  ),
  'life-accident' => 
  array (
    'label' => 'ประกันชีวิตและอุบัติเหตุ',
    'products' => 
    array (
      0 => 
      array (
        'slug' => 'be-sure',
        'title' => 'Be Sure',
        'desc' => 'ประกันคุ้มครองชีวิต มั่นใจชัวร์ วางแผนความคุ้มครองชีวิต',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/be-sure/',
      ),
      1 => 
      array (
        'slug' => 'heritage-plus',
        'title' => 'FWD Heritage Plus',
        'desc' => 'ผลิตภัณฑ์เอฟดับบลิวดี เฮอริเทจ พลัสคุ้มครองชีวิตสูงถึงอายุ 99 ปี พร้อมทางเลือกรับผลประโยชน์ก่อนครบกำหนดสัญญา เพิ่มความคุ้มครองกรณี',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/heritage-plus/',
      ),
      2 => 
      array (
        'slug' => 'prakan-kon-jing',
        'title' => 'ประกันคนจริง',
        'desc' => 'ประกันอุบัติเหตุ ประกันคนจริง ออกแบบด้วย AI',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/prakan-kon-jing/',
      ),
      3 => 
      array (
        'slug' => 'prakan-kon-kla',
        'title' => 'ประกันคนกล้า',
        'desc' => 'ประกันอุบัติเหตุ ประกันคนกล้า',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/prakan-kon-kla/',
      ),
      4 => 
      array (
        'slug' => 'prakan-kon-kla-max',
        'title' => 'ประกันคนกล้า MAX',
        'desc' => 'ประกันอุบัติเหตุ ความคุ้มครองสูง แมกซ์',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/prakan-kon-kla-max/',
      ),
      5 => 
      array (
        'slug' => 'prakan-kon-klang',
        'title' => 'ประกันคนแกร่ง',
        'desc' => 'ประกันอุบัติเหตุ ประกันคนแกร่ง',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/prakan-kon-klang/',
      ),
      6 => 
      array (
        'slug' => 'value-protector',
        'title' => 'Value Protector',
        'desc' => 'ประกันคุ้มครองชีวิต คุ้มครอง คุ้มค่า คุ้มภัย',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/value-protector/',
      ),
      7 => 
      array (
        'slug' => 'whole-life',
        'title' => 'Whole Life 99/99',
        'desc' => 'ประกันคุ้มครองชีวิตแบบตลอดชีพ 99/99',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/whole-life/',
      ),
      8 => 
      array (
        'slug' => 'whole-life-extra',
        'title' => 'Whole Life Extra',
        'desc' => 'ประกันตลอดชีพ คุ้มชีวีเอ็กซ์ตร้า ผลประโยชน์เพิ่มเติม',
        'fwd_url' => 'https://www.fwd.co.th/th/life-and-accident-insurance/whole-life-extra/',
      ),
    ),
  ),
  'savings' => 
  array (
    'label' => 'ประกันสะสมทรัพย์',
    'products' => 
    array (
      0 => 
      array (
        'slug' => 'fwd-for-saving-25-15',
        'title' => 'FWD For Saving 25/15',
        'desc' => 'ออมทรัพย์ 25/15 ตามเป้าหมาย',
        'fwd_url' => 'https://www.fwd.co.th/th/savings-insurance/fwd-for-saving-25-15/',
      ),
      1 => 
      array (
        'slug' => 'fwd-life-saving-18-9',
        'title' => 'FWD Life Saving 18/9',
        'desc' => 'ประกันสะสมทรัพย์ Life Saving 18/9',
        'fwd_url' => 'https://www.fwd.co.th/th/savings-insurance/fwd-life-saving-18-9/',
      ),
      2 => 
      array (
        'slug' => 'fwd-life-saving-30-15',
        'title' => 'FWD Life Saving 30/15',
        'desc' => 'สะสมทรัพย์ระยะยาว 30/15',
        'fwd_url' => 'https://www.fwd.co.th/th/savings-insurance/fwd-life-saving-30-15/',
      ),
      3 => 
      array (
        'slug' => 'fwd-power-saving',
        'title' => 'FWD Power Saving 12/6',
        'desc' => 'สะสมทรัพย์ จ่าย 6 ปี ครบ 12 ปี',
        'fwd_url' => 'https://www.fwd.co.th/th/savings-insurance/fwd-power-saving/',
      ),
      4 => 
      array (
        'slug' => 'fwd-savvy-pension',
        'title' => 'FWD Savvy Pension',
        'desc' => 'ผลิตภัณฑ์เอฟดับบลิวดี แซฟวี เพนชันเตรียมความพร้อมให้ชีวิตเกษียณ ด้วยเงินบำนาญต่อเนื่องทุกปี ยาวถึงอายุ 90 ปี มั่นใจทุกช่วงอายุกับเงินบำนาญที่เพิ่มขึ้นจนสูงสุ...',
        'fwd_url' => 'https://www.fwd.co.th/th/savings-insurance/fwd-savvy-pension/',
      ),
      5 => 
      array (
        'slug' => 'fwd-sure-pension',
        'title' => 'FWD Sure Pension',
        'desc' => 'ผลิตภัณฑ์เอฟดับบลิวดี ชัวร์ เพนชันรับเงินบำนาญสูงถึง 20% ของทุนประกันภัย ต่อเนื่องจนถึงอายุ 85 ปี เพื่อชีวิตหลังเกษียณที่อิสระ และมีคุณภาพในแบบที่คุณวางแผนไว้',
        'fwd_url' => 'https://www.fwd.co.th/th/savings-insurance/fwd-sure-pension/',
      ),
      6 => 
      array (
        'slug' => 'lifetime-return',
        'title' => 'FWD Lifetime Return 99/15',
        'desc' => 'ผลิตภัณฑ์เอฟดับบลิวดี ไลฟ์ไทม์ รีเทิร์น 99/15ประกันชีวิตที่ให้ความคุ้มครองแบบตลอดชีพ เพื่อสร้างความมั่นคงรองรับอนาคตพร้อมรับผลประโยชน์ระยะยาวอย่างต่อเนื่องทุ...',
        'fwd_url' => 'https://www.fwd.co.th/th/savings-insurance/lifetime-return/',
      ),
    ),
  ),
  'investment' => 
  array (
    'label' => 'ประกันชีวิตควบการลงทุน',
    'products' => 
    array (
      0 => 
      array (
        'slug' => 'fwd-freedom-linked-plus',
        'title' => 'FWD Freedom Linked Plus 15/5',
        'desc' => 'Freedom Linked Plus เพิ่มความยืดหยุ่นการลงทุน',
        'fwd_url' => 'https://www.fwd.co.th/th/investment-linked-insurance/fwd-freedom-linked-plus/',
      ),
      1 => 
      array (
        'slug' => 'fwd-future-linked-99-9',
        'title' => 'FWD Future Linked 99/9',
        'desc' => 'ประกันชีวิตควบการลงทุน Future Linked 99/9',
        'fwd_url' => 'https://www.fwd.co.th/th/investment-linked-insurance/fwd-future-linked-99-9/',
      ),
      2 => 
      array (
        'slug' => 'fwd-one-linked',
        'title' => 'FWD One Linked',
        'desc' => 'ลงทุนผ่านกองทุนรวมยูนิตลิงก์ แผน One Linked',
        'fwd_url' => 'https://www.fwd.co.th/th/investment-linked-insurance/fwd-one-linked/',
      ),
      3 => 
      array (
        'slug' => 'fwd-ultra-linked-99-99',
        'title' => 'FWD Ultra Linked 99/99',
        'desc' => 'ความคุ้มครองชีวิตควบการลงทุน Ultra Linked',
        'fwd_url' => 'https://www.fwd.co.th/th/investment-linked-insurance/fwd-ultra-linked-99-99/',
      ),
    ),
  ),
);
